version: '3'
services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    ports:
      - "5000:5000"
    
  centos:
    build:
      context: .
      dockerfile: Dockerfile.cent
    ports:
      - "5001:5000"
